server:
  port: 8081
  
spring:
  application:
    name: 'supplier'
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://8761/eureka 