server:
  port: 8081
  
spring:
  datasource:
    username: root
    password: ativ$webmb
    url: jdbc:mysql://localhost:3306/supplie
  jpa:
    hibernate:
      ddl-auto: create
  application:
    name: 'supplier'
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://8761/eureka 